name: auto-post

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - run: pip install -r requirements.txt

    - run: python main.py
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        LIVEDOOR_ID: ${{ secrets.LIVEDOOR_ID }}
        LIVEDOOR_PASS: ${{ secrets.LIVEDOOR_PASS }}